### PR TITLE
Add py.typed

### PR DESCRIPTION
**Pull request by eggplants**
I added blank `py.typed` file into distribution package.

When I using pysub2 `mypy` raises the error because pysub2 does not [PEP 561 typed marker file](https://peps.python.org/pep-0561/#packaging-type-information):

```
subt/main.py:7:1: error: Skipping analyzing "pysubs2": module is installed, but
missing library stubs or py.typed marker  [import-untyped]
    import pysubs2
```

`pysubs2` type annotations are [being checked](https://github.com/tkarabela/pysubs2/blob/dd3a89137f0764c7b266c7a74c8e86465f7c0271/.github/workflows/main.yml#L37) with `mypy --strict`, so it can be available.

### CODE REVIEW

**Comment by eggplants** [comment]
`py.typed` has been added successfully in CI.

https://github.com/tkarabela/pysubs2/actions/runs/10126226229/job/28002628263?pr=98#step:10:196

**Comment by tkarabela** [comment]
Thanks! :)

**Comment by eggplants** [comment]
I would appreciate it if you could create a new release to PyPI. Thank you in advance.

**Comment by eggplants** [comment]
Confirmed built package includes `py.typed`:

<details>

```shellsession
$ git clone --depth 1 https://github.com/tkarabela/pysubs2
$ cd pysubs2
$ pipx install build
$ pyproject-build
...
Successfully built pysubs2-1.7.3.tar.gz and pysubs2-1.7.3-py3-none-any.whl
$ unar dist/pysubs2-1.7.3.tar.gz
$ tree pysubs2-1.7.3/
pysubs2-1.7.3/
├── LICENSE.txt
├── MANIFEST.in
├── PKG-INFO
├── pyproject.toml
├── pysubs2
│   ├── cli.py
│   ├── common.py
│   ├── exceptions.py
│   ├── formats
│   │   ├── base.py
│   │   ├── __init__.py
│   │   ├── jsonformat.py
│   │   ├── microdvd.py
│   │   ├── mpl2.py
│   │   ├── subrip.py
│   │   ├── substation.py
│   │   ├── tmp.py
│   │   ├── webvtt.py
│   │   └── whisper.py
│   ├── __init__.py
│   ├── __main__.py
│   ├── py.typed
│   ├── ssaevent.py
│   ├── ssafile.py
│   ├── ssastyle.py
│   └── time.py
├── pysubs2.egg-info
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   └── top_level.txt
├── README.md
├── setup.cfg
└── tests
    ├── data
    │   ├── EBGaramond08-Italic.ttf
    │   ├── EBGaramond08-Regular.ttf
    │   ├── LICENSE.txt
    │   ├── subtitle_with_attached_fonts_aegisub.ass
    │   ├── subtitle_with_attached_fonts_no_events.ass
    │   ├── subtitle_with_attached_fonts_pysubs2_ref.ass
    │   ├── subtitle_with_attached_images_aegisub.ass
    │   └── subtitle_with_attached_images_pysubs2_ref.ass
    ├── test_attachment.py
    ├── test_cli.py
    ├── test_common.py
    ├── test_parse_tags.py
    ├── test_ssaevent.py
    ├── test_ssafile.py
    ├── test_ssastyle.py
    └── test_time.py

6 directories, 47 files
```

</details>

**Comment by tkarabela** [comment]
> I would appreciate it if you could create a new release to PyPI. Thank you in advance.

Sure, a new version should be out by Christmas :) I want to add a few other things as well.

**Pull request merged**
